# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 614)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(13, -1, -1, 10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_table = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_table.setTitle("")
        self.groupBox_table.setFlat(True)
        self.groupBox_table.setObjectName("groupBox_table")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_table)
        self.verticalLayout_2.setContentsMargins(9, 16, 12, -1)
        self.verticalLayout_2.setSpacing(13)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_results = QtWidgets.QTableWidget(parent=self.groupBox_table)
        self.table_results.setShowGrid(True)
        self.table_results.setColumnCount(5)
        self.table_results.setObjectName("table_results")
        self.table_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(4, item)
        self.table_results.horizontalHeader().setCascadingSectionResizes(False)
        self.table_results.horizontalHeader().setDefaultSectionSize(93)
        self.table_results.horizontalHeader().setMinimumSectionSize(20)
        self.table_results.verticalHeader().setCascadingSectionResizes(False)
        self.table_results.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_2.addWidget(self.table_results)
