# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 614)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(13, -1, -1, 10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_table = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_table.setTitle("")
        self.groupBox_table.setFlat(True)
        self.groupBox_table.setObjectName("groupBox_table")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_table)
        self.verticalLayout_2.setContentsMargins(9, 16, 12, -1)
        self.verticalLayout_2.setSpacing(13)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_results = QtWidgets.QTableWidget(self.groupBox_table)
        self.table_results.setShowGrid(True)
        self.table_results.setColumnCount(5)
        self.table_results.setObjectName("table_results")
        self.table_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(4, item)
        self.table_results.horizontalHeader().setCascadingSectionResizes(False)
        self.table_results.horizontalHeader().setDefaultSectionSize(93)
        self.table_results.horizontalHeader().setMinimumSectionSize(20)
        self.table_results.verticalHeader().setCascadingSectionResizes(False)
        self.table_results.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_2.addWidget(self.table_results)
        self.pushButton_copydata = QtWidgets.QPushButton(self.groupBox_table)
        self.pushButton_copydata.setObjectName("pushButton_copydata")
        self.verticalLayout_2.addWidget(self.pushButton_copydata, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.groupBox_table, 1, 1, 1, 3)
        self.groupBox_showdata = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_showdata.setTitle("")
        self.groupBox_showdata.setFlat(True)
        self.groupBox_showdata.setObjectName("groupBox_showdata")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_showdata)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_Reflections = QtWidgets.QGraphicsView(self.groupBox_showdata)
        self.view_Reflections.setObjectName("view_Reflections")
        self.verticalLayout.addWidget(self.view_Reflections)
        self.pushButton_show_Reflections_Data = QtWidgets.QPushButton(self.groupBox_showdata)
        self.pushButton_show_Reflections_Data.setObjectName("pushButton_show_Reflections_Data")
        self.verticalLayout.addWidget(self.pushButton_show_Reflections_Data, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.groupBox_showdata, 0, 0, 1, 4)
        self.view_colorSpace = QtWidgets.QGraphicsView(self.centralwidget)
        self.view_colorSpace.setObjectName("view_colorSpace")
        self.gridLayout.addWidget(self.view_colorSpace, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Create menu bar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 24))
        self.menubar.setObjectName("menubar")
        
        # Create menus
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_file.setTitle("File")
        
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_edit.setTitle("Edit")
        
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_help.setTitle("Help")
        
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # Create actions
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionImport.setText("Import...")
        self.actionImport.setShortcut("Ctrl+O")
        
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExport.setText("Export...")
        self.actionExport.setShortcut("Ctrl+E")
        
        self.actionPlot = QtGui.QAction(MainWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actionPlot.setText("Plot...")
        self.actionPlot.setShortcut("Ctrl+P")
        
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSettings.setText("Settings...")
        self.actionSettings.setShortcut("Ctrl+.")
        self.actionSettings.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        
        self.actionCopy_all_data = QtGui.QAction(MainWindow)
        self.actionCopy_all_data.setObjectName("actionCopy_all_data")
        self.actionCopy_all_data.setText("Copy ALL Data")
        self.actionCopy_all_data.setShortcut("Ctrl+C")
        
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionClear.setText("Clear")
        self.actionClear.setShortcut("Ctrl+K")
        
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout.setText("About...")
        self.actionAbout.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionManual.setText("Manual...")
        
        # Add actions to menus
        self.menu_file.addAction(self.actionImport)
        self.menu_file.addAction(self.actionExport)
        self.menu_file.addAction(self.actionPlot)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionSettings)
        
        self.menu_edit.addAction(self.actionCopy_all_data)
        self.menu_edit.addAction(self.actionClear)
        
        self.menu_help.addAction(self.actionAbout)
        self.menu_help.addAction(self.actionManual)
        
        # Add menus to menubar
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aleksameter App"))
        item = self.table_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.table_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "x"))
        item = self.table_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "y"))
        item = self.table_results.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "sRGB lin"))
        item = self.table_results.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "sRGB gamma"))
        self.pushButton_copydata.setText(_translate("MainWindow", "Copy to Clipboard"))
        self.pushButton_show_Reflections_Data.setText(_translate("MainWindow", "Show Reflections Data"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_edit.setTitle(_translate("MainWindow", "Edit"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.actionImport.setText(_translate("MainWindow", "Import..."))
        self.actionExport.setText(_translate("MainWindow", "Export..."))
        self.actionPlot.setText(_translate("MainWindow", "Plot..."))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.actionCopy_all_data.setText(_translate("MainWindow", "Copy ALL Data"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionManual.setText(_translate("MainWindow", "Manual..."))
